### ISSUE TITLE
Nav Clock Heats

### ISSUE THREAD

**Issue by Notenoughmail** [HyperDashPony/FirmaCiv#29]
The heat definition for the [nav clock](https://github.com/HyperDashPony/FirmaCiv/blob/1.20.x/src/main/resources/data/firmaciv/tfc/item_heats/nav_clock.json#L3) and the [unfinished nav clock](https://github.com/HyperDashPony/FirmaCiv/blob/1.20.x/src/main/resources/data/firmaciv/tfc/item_heats/unfinished_nav_clock.json#L3) use `utem` in their ingredients, instead of `item`

**Comment by HyperDashPony** [comment]
Version please!!
