### ISSUE TITLE
Crashes on dedicated server

### ISSUE THREAD

**Issue by karltroid51** [HyperDashPony/FirmaCiv#4]
Attached are the logs detailing what happened. something to do about player renderer issues not being registered properly for dedicated servers?

[debug.log](https://github.com/HyperDashPony/FirmaCiv/files/12011335/debug.log)
[latest.log](https://github.com/HyperDashPony/FirmaCiv/files/12011336/latest.log)

**Comment by HyperDashPony** [comment]
Attempted a fix! 0.0.42
