### ISSUE TITLE
Compass points in wrong direction

### ISSUE THREAD

**Issue by zhwith** [HyperDashPony/FirmaCiv#41]
The compass in the screenshot should be pointing to the right.
Sme testing revealed that the arrow is always flipped horizontally.
![2024-01-24_11 49 47](https://github.com/HyperDashPony/FirmaCiv/assets/97792022/b56e5042-cfab-4843-a8f3-9c2afc59d3cf)

**Comment by HyperDashPony** [comment]
I can't reproduce this, please let me know what version you are using and the conditions you encountered this in!

**Comment by Traister101** [comment]
You'll need to share what version of FirmaCiv you are using

**Comment by HyperDashPony** [comment]
I double checked this, there's not even anything wrong with your screenshot. You're looking west, the map icon is facing west, and the compass is facing west.
