### ISSUE TITLE
Compass rotates the wrong way

### ISSUE THREAD

**Issue by rhino1998** [HyperDashPony/FirmaCiv#44]
The true north compass only points north when pointing either north or south because the compass rotates the wrong way. The compass needle rotates clockwise when you rotate clockwise. It should rotate counterclockwise when you rotate clockwise

North - points north
![2024-01-31_00 31 56](https://github.com/HyperDashPony/FirmaCiv/assets/9094640/1f31d556-96e9-410c-8ea1-46171fe224f4)

West - points south
![2024-01-31_00 32 02](https://github.com/HyperDashPony/FirmaCiv/assets/9094640/f9979440-5378-410e-9ab2-417225affaa4)

East - points south
![2024-01-31_00 32 05](https://github.com/HyperDashPony/FirmaCiv/assets/9094640/0f4323ab-f9cb-4e81-9241-60b4a6442c7d)

South - points north
![2024-01-31_00 32 08](https://github.com/HyperDashPony/FirmaCiv/assets/9094640/f9eab7ec-3d17-40ff-b204-7e1fb4315a7d)

**Comment by HyperDashPony** [comment]
Someone reported this but I wasn't able to reproduce it, can you send screenshots from a world with reduceDebugInfo set back to true?

**Comment by rhino1998** [comment]
South - compass needle (correctly) points backwards towards north
![2024-01-31_14 32 07](https://github.com/HyperDashPony/FirmaCiv/assets/9094640/d15f52cb-8519-4cf0-911e-cabb452e7405)

West - compass needle (incorrectly) points left towards south 
![2024-01-31_14 32 12](https://github.com/HyperDashPony/FirmaCiv/assets/9094640/fcda69ce-2493-4c46-8292-b1e972cedb79)

North - compass needle (correctly) points forward towards north
![2024-01-31_14 32 19](https://github.com/HyperDashPony/FirmaCiv/assets/9094640/66c33cdb-6582-4758-be97-742f01879ee8)

East - compass needle (incorrectly) points right towards south
![2024-01-31_14 32 23](https://github.com/HyperDashPony/FirmaCiv/assets/9094640/69d4577d-8dd4-4bbd-8054-1c3e46820c0c)

**Comment by rhino1998** [comment]
This is happening in every world for me

**Comment by rhino1998** [comment]
Pretty sure a negative sign here on rotation would fix it. I'll try it out https://github.com/HyperDashPony/FirmaCiv/blob/ccb5e527cd344534dbc67b4b42e6bc34201bd480/src/main/java/com/alekiponi/firmaciv/client/FirmacivClientEvents.java#L97
