### ISSUE TITLE
Sailing wind in multiplayer

### ISSUE THREAD

**Issue by rhino1998** [HyperDashPony/FirmaCiv#45]
This is probably a TFC bug, but the wind does not sync properly in multiplayer, but the wind speed is 0 and the direction is always north.

![2024-01-31_00 31 56](https://github.com/HyperDashPony/FirmaCiv/assets/9094640/50697a57-9527-4426-b950-7835d437f2dd)

**Comment by rhino1998** [comment]
Server misconfiguration, woops. Not a bug

**Comment by HyperDashPony** [comment]
Yeah, there's no TFC wind in Vanilla worlds, I added a small hardcoded wind for vanilla worlds just for testing!
