### ISSUE TITLE
you need to add a config to be able to disable disabling recipes

### ISSUE THREAD

**Issue by FriendlyCube** [HyperDashPony/FirmaCiv#5]
I'm playing in a modpack on 1.18.2 with tfk, your addon and an addon for ships: "TerraFirmaShips"
the mod adds 3 types of ships in the crafting of which boats from minecraft are used
![image](https://github.com/HyperDashPony/FirmaCiv/assets/112543401/43a37093-ae07-4b2f-bbeb-4d038badfd33)
![image](https://github.com/HyperDashPony/FirmaCiv/assets/112543401/8d24d5b1-0ceb-4d12-8ddd-0631dcd8c103)

boat crafting is disabled by your mod, so I'm asking you to create a config to be able to disable disabling crafting

**Comment by HyperDashPony** [comment]
That's planned, that said, it won't really be compatible with Small Ships in the future, so it might benefit you to just use a datapack to add new ship recipes.
