### ISSUE TITLE
Firmaciv encountered an error during the sided_setup phase

### ISSUE THREAD

**Issue by MrHiTech123** [HyperDashPony/FirmaCiv#57]
Keep getting a crash by that name. Here's the crash report:
[crash-2024-03-04_22.27.25-fml.txt](https://github.com/HyperDashPony/FirmaCiv/files/14489962/crash-2024-03-04_22.27.25-fml.txt)

The crash is infrequent (probably around 1/4 - 1/3 of the times I launch Minecraft) so it can usually be fixed by closing and relaunching it.

**Comment by HyperDashPony** [comment]
I'll look into this, I haven't seen it... can you help me out by doing a binary search test with that modlist? It might be a conflict with one of those mods.

**Comment by MrHiTech123** [comment]
I’ll try, though the crash happens inconsistently enough that I don’t know how reliable a negative will be. 

I also have a bunch of other stuff I’m supposed to be doing this week but I’ll do what I can

**Comment by MrHiTech123** [comment]
So I tried loading my mods up today, and it crashed the first time, but then after that the crash could not be replicated: I loaded minecraft over and over again 10 times in a row, and it worked perfectly every time except the first. The second-to-final time, I opened a world and played around a bit in it, and the error still did not happen the final time.

My current theory is that the error happens once per day (this is a terrible theory, but I can't think of a better one), but I'll have to wait until tomorrow to prove or disprove that.

In the meantime, I don't think I'll be able to do the binary search test due to my inability to produce anything other than a false negative.

Edit: The error happened more than once in a day so that's probably not the answer.

**Comment by HyperDashPony** [comment]
Okay, I'll keep this in the issue tracker and get to it when I can.

**Comment by MrHiTech123** [comment]
Thanks!
Also, I'm pretty sure it's the 1.20 Musket Mod. I got an error that seems to be the exact same, except for the mod name (MusketMod instead of FirmaCiv, of course) and some numbers (memory addresses?). Here's that log file if you're interested (though I'll put this on their issue tracker too).
[crash1.txt](https://github.com/HyperDashPony/FirmaCiv/files/14610782/crash1.txt)

**Comment by MrHiTech123** [comment]
Nevermind, that's the 1.18 version of the mod. The 1.20 version appears to be closed-source.
