### ISSUE TITLE
The new update have Resolution error

### ISSUE THREAD

**Issue by khiroYT** [HyperDashPony/FirmaCiv#65]
I updated the mod and I keep crashing. and it shows me an error about Changing the resolution to 1920 × 1080, I don't get it but I tried reverting back to previous version and everything went well

**Comment by DRAGNIZ** [comment]
> I updated the mod and I keep crashing. and it shows me an error about Changing the resolution to 1920 × 1080, I don't get it but I tried reverting back to previous version and everything went well

same.

**Comment by HyperDashPony** [comment]
Fixed soon
